const {test}=require('node:test');const assert=require('node:assert/strict');const {sendCheckinInstructions}=require('./checkin-instructions');
function fixture(channel='app',facility='csp-toledo-main'){
 const messages=[],texts=[],uploads=[];
 const db={storage:{from:()=>({upload:async(p,data,opts)=>{uploads.push({p,size:data.length,type:opts.contentType});return{}},createSignedUrl:async p=>({data:{signedUrl:'https://example.test/'+p}})})},from(){let value,op='insert';const q={insert(v){value=v;return q},select(){return q},single(){return q},update(v){value=v;op='update';return q},eq(){return q},then(resolve){if(op==='update')return Promise.resolve({}).then(resolve);if(messages.some(m=>m.client_message_id===value.client_message_id))return Promise.resolve({error:{code:'23505'}}).then(resolve);messages.push(value);return Promise.resolve({data:{id:messages.length}}).then(resolve)}};return q;}};
 const deps={db,twilio:{messages:{create:async m=>{texts.push(m);return{sid:'SM'+texts.length,status:'sent'}}}},messagingServiceSid:'MGtest',publicBaseUrl:'https://example.test',conversation:{id:'visit',user_id:channel==='app'?'driver':null,channel,facility_id:facility,sms_phone_e164:'+15555550100'},staffId:'staff',visitType:'pickup'};
 return{messages,texts,uploads,deps};
}
for(const channel of ['app','sms'])test(channel+' receives map and exact PPE image once across repeated check-ins',async()=>{const f=fixture(channel);await sendCheckinInstructions(f.deps);await sendCheckinInstructions(f.deps);assert.equal(f.messages.length,2);assert.equal(f.messages[1].body,'PPE requirements');assert.match(f.messages[1].attachment_path,/ray-ppe.png$/);assert.equal(f.messages[1].attachment_content_type,'image/png');assert.ok(f.messages[1].attachment_size_bytes>1000);assert.match(f.messages[0].attachment_path,/shipping-map.jpg$/);assert.equal(f.texts.length,channel==='sms'?2:0);if(channel==='sms'){assert.match(f.texts[0].mediaUrl[0],/shipping-map.jpg$/);assert.match(f.texts[1].mediaUrl[0],/ray-ppe.png$/);}});
test('other facility receives PPE without the wrong property map',async()=>{const f=fixture('app','csp-toledo-enterprise');await sendCheckinInstructions(f.deps);assert.equal(f.messages[0].attachment_path,undefined);assert.match(f.messages[1].attachment_path,/ray-ppe.png$/);});
test('dropoff does not receive pickup instructions or PPE messages',async()=>{const f=fixture();f.deps.visitType='dropoff';await sendCheckinInstructions(f.deps);assert.equal(f.messages.length,0);assert.equal(f.uploads.length,0);});
