'use strict';
function allowed(form,user,roles){return roles.includes('admin')||form.recipients.includes(String(user.email||'').toLowerCase());}
function flatten(value,prefix='',out={}){for(const[k,v]of Object.entries(value)){const key=prefix?prefix+'.'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flatten(v,key,out);else out[key]=Array.isArray(v)?JSON.stringify(v):v;}return out;}
function cell(value){let s=value==null?'':String(value);if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function csv(rows,defaults){const flat=rows.map(r=>flatten(r)),keys=[...new Set([...defaults,...flat.flatMap(Object.keys)])];return '\uFEFF'+[keys.map(cell).join(','),...flat.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')+'\r\n';}
function register(app,{auth,roleRows,roleNames,chart,recipients,env=process.env,request=fetch}){
 const catalog=[];
 const add=(id,name,url,table,columns,who,options={})=>catalog.push({id,name,url,table,columns,recipients:who,db:chart,date:'submitted_at',pk:'id',...options});
 add('fall-festival','CSP Family Fall Festival','/fall-festival/','fall_festival_signups','submitted_at,employee_name,attendance,family_count,chili',['lindsey@coilsteelprocessing.com','kim@coilsteelprocessing.com'],{db:auth,pk:'submission_token'});
 add('fantasy-football','Fantasy Football Signup','/fantasyfootballsignup/','fantasy_football_signups','submitted_at,season,name,email,phone',recipients.fantasy);
 for(const[key,name,url,who]of [['shift_report','End of Shift Report','/shiftreport/',recipients.shift],['forklift_inspection','Forklift Inspection','/forklift-inspections/',recipients.forklift],['crane_inspection','Crane Inspection','/crane-inspections/',recipients.crane],['operational_inspection','RBI Operational Checklist','https://pro.coilsteelprocessing.com/rbi-checklist.html',recipients.pro],['production_intake','Production Entry','https://pro.coilsteelprocessing.com/production-entry.html',recipients.pro]])add(key,name,url,'pro_form_submissions','submitted_at,submitted_by_email,submission_date,shift,department,line,notes,dimensions,metrics,payload',who,{filter:['form_key',key]});
 add('processing-inquiry','New Line Processing Inquiry','/new-line/#contact','expansion_leads','submitted_at,name,company,email,phone,material_need,opportunity_timing,message',recipients.expansion);
 add('pickem-signups','NFL Pick’em Signup','/nfl-pickem/auth.html','pickem_signup_links','created_at,email,display_name,consumed_at,expires_at',['todd@coilsteelprocessing.com'],{db:auth,date:'created_at',pk:'token_hash'});
 add('todd-requests','Todd Work Requests','https://bi.coilsteelprocessing.com/todd.html','todd_work_requests','created_at,project,requested_by,requested_by_email,date_requested,date_needed,priority,status,notes,completed_at',['todd@coilsteelprocessing.com'],{date:'created_at'});
 add('maintenance','Maintenance Response','https://bi.coilsteelprocessing.com/newmaintenance.html','pro_maintenance_orders','reported_at,order_code,status,priority,asset_name,issue_category,issue_notes,reported_by_email,reported_by_name,acknowledged_at,acknowledged_by,completed_at,completed_by,corrective_action,completion_notes,parts_used,downtime_minutes',recipients.maintenance,{date:'reported_at'});
 add('progress-updates','New Line Progress Updates','/new-line/#line-progress-updates',null,'created_at,email,first_name,last_name,unsubscribed',['todd@coilsteelprocessing.com'],{provider:'resend'});
 async function verify(req,res,next){res.set('Cache-Control','no-store');try{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'Please sign in.'});const{data,error}=await auth.auth.getUser(token);if(error||!data?.user)return res.status(401).json({error:'Your session expired. Please sign in again.'});req.formsUser=data.user;req.formsRoles=roleNames(await roleRows(data.user.id));next();}catch{return res.status(503).json({error:'Unable to verify access. Try again.'})}}
 async function contacts(){if(!env.RESEND_API_KEY||!env.RESEND_PROGRESS_SEGMENT_ID)throw Error('Subscriber storage is unavailable.');let after='',rows=[];for(;;){const url=new URL('https://api.resend.com/segments/'+encodeURIComponent(env.RESEND_PROGRESS_SEGMENT_ID)+'/contacts');url.searchParams.set('limit','100');if(after)url.searchParams.set('after',after);const r=await request(url,{headers:{Authorization:'Bearer '+env.RESEND_API_KEY},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Subscriber export is temporarily unavailable.');const d=await r.json();for(const c of d.data||[])rows.push(Object.fromEntries(['created_at','email','first_name','last_name','unsubscribed'].map(k=>[k,c[k]])));if(!d.has_more)break;const next=d.data?.at(-1)?.id;if(!next||next===after)throw Error('Subscriber pagination failed.');after=next;}return rows;}
 function query(f,cols,options){if(!f.db)throw Error('Form storage is unavailable.');let q=f.db.from(f.table).select(cols,options);if(f.filter)q=q.eq(...f.filter);return q;}
 app.get('/api/forms-hub',verify,async(req,res)=>{const forms=await Promise.all(catalog.filter(f=>allowed(f,req.formsUser,req.formsRoles)).map(async f=>{const info={id:f.id,name:f.name,url:f.url};try{if(f.provider){const rows=await contacts();return{...info,count:rows.length}}const{count,error}=await query(f,f.pk,{count:'exact',head:true});if(error)throw error;return{...info,count};}catch{return{...info,count:null,error:'Results temporarily unavailable'}}}));res.json({forms,email:req.formsUser.email});});
 app.get('/api/forms-hub/:id.csv',verify,async(req,res)=>{const f=catalog.find(f=>f.id===req.params.id);if(!f||!allowed(f,req.formsUser,req.formsRoles))return res.status(403).json({error:'You do not have access to these results.'});try{let rows=[];if(f.provider)rows=await contacts();else{const cutoff=new Date().toISOString();for(let offset=0;;offset+=500){const{data,error}=await query(f,f.columns).lte(f.date,cutoff).order(f.date,{ascending:true}).order(f.pk,{ascending:true}).range(offset,offset+499);if(error)throw error;rows.push(...data);if(data.length<500)break;}}res.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="csp-${f.id}-${new Date().toISOString().slice(0,10)}.csv"`,'X-Content-Type-Options':'nosniff'});res.send(csv(rows,f.columns.split(',').filter(k=>!['payload','metrics','dimensions'].includes(k))));}catch(error){console.error('Forms export:',f.id,error.message);res.status(503).json({error:'Results could not be downloaded. Please try again.'})}});
}
module.exports={register,allowed,csv};
