const {test}=require('node:test'),assert=require('node:assert/strict');const {analyze,groupFor,normalizeReports}=require('./sad-v2');
const end='2026-10-06T12:00:00Z';
function raw(type='AL'){return {end,first:'2026-08-01T00:00:00Z',latest:end,patterns:[{alarm_type:type,plc_tag:'Uncoiler_500_MT',message:'Uncoiler Coil Slip',n1:8,p1:2,n7:20,p7:5,n30:30,p30:10,last_seen:end}],daily:[{alarm_type:type,plc_tag:'Uncoiler_500_MT',message:'Uncoiler Coil Slip',day:'2026-10-05',n:12},{alarm_type:type,plc_tag:'Uncoiler_500_MT',message:'Uncoiler Coil Slip',day:'2026-10-06',n:8}]};}
test('uses PLC equipment tag rather than misleading message',()=>assert.equal(groupFor({plc_tag:'Entry_Coil_Stage_500_MT',message:'Uncoiler Jog'}),'entry'));
test('unknown PLC requires mapping review',()=>assert.equal(groupFor({plc_tag:'NEW_ABC',message:'shear'}),'unmapped'));
test('MC volume never becomes a failure candidate',()=>assert.equal(analyze(raw('MC'),[],7).groups.find(g=>g.id==='uncoiler').reviewCount,0));
test('rising AL counts have an auditable prior comparison',()=>{const p=analyze(raw(),[],7).groups.find(g=>g.id==='uncoiler').patterns[0];assert.equal(p.current,20);assert.equal(p.previous,5);assert.equal(p.ratio,4);assert.ok(p.reviewable)});
test('report revision deduplicated, equipment + date correlation retained',()=>{const r={submission_id:1,report_date:'2026-10-05',shift:'First',operator:'Joe',submitted_at:'2026-10-05T12:00:00Z',maintenance_reason:'uncoiler coil slip'};const rs=[r,{...r,submission_id:2,submitted_at:'2026-10-05T13:00:00Z'}];assert.equal(normalizeReports(rs).length,1);const g=analyze(raw(),rs,7).groups.find(g=>g.id==='uncoiler');assert.equal(g.reports[0].submission_id,2);assert.equal(g.reports[0].correlation,'Equipment mention + same date')});
test('unrelated report is not called an alarm match',()=>{const d=analyze(raw(),[{report_date:'2026-10-05',operator:'Joe',maintenance_reason:'forklift battery'}],7);assert.equal(d.groups.find(g=>g.id==='uncoiler').reports.length,0);assert.equal(d.unmatchedReports.length,1)});
test('partial baseline explicitly identified',()=>assert.equal(analyze({...raw(),first:'2026-10-05T00:00:00Z'},[],30).coverage.partial,true));
